
# read_value, write_value are imported from monitor_wrapper.so generated by Makefile
from .monitor_wrapper import read_value as _read_value, write_value as _write_value



def read_value(address: int) -> int:
    assert address   >= 0, "address is positive int"
    assert address%4 == 0, "proper address is 4 multiple"
    result = _read_value(address)
    return result

def write_value(address: int, value: int):
    assert address   >= 0, "address is positive int"
    assert address%4 == 0, "proper address is 4 multiple"
    _write_value(address, value)
    return
